### ISSUE TITLE
Support async interface

### ISSUE THREAD

**Issue by ikrivosheev** [michaelklishin/rabbitmq-http-api-rs#27]
Hello! Thank you for the great library! I want to add async interface. Is it ok?

**Comment by michaelklishin** [comment]
@ikrivosheev I cannot comment on such a terse problem definition. 

The biggest headache around supporting an async API is the dependencies. So it will have to be an opt-in feature using, for example, some Tokio bits.

Otherwise I have no objections, we have [HTTP API clients](https://github.com/rabbitmq/hop/) that support two versions and it was the goal with the namespacing used here.

**Comment by michaelklishin** [comment]
I see that in https://github.com/michaelklishin/rabbitmq-http-api-rs/pull/26, even the blocking client becomes optional. In which case making the dependency-heavy async one optional is probably what you had in mind anyway.

**Comment by ikrivosheev** [comment]
> I see that in https://github.com/michaelklishin/rabbitmq-http-api-rs/pull/26, even the blocking client becomes optional. In which case making the dependency-heavy async one optional is probably what you had in mind anyway.

Yes, you are right. I meant async client would be optional
